# ruff.toml
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".ipynb_checkpoints",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pyenv",
  ".pytest_cache",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  ".vscode",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "site-packages",
  "venv",
  "alembic",
]
lint.select = ["ALL"]
lint.ignore = [
  "BLE001",
  "SIM108",
  "ERA001",
  "F401",
  "C901",
  "PLR0912",
  "G004",
  "PGH004",
  "ANN201",
  "ANN205",
  "COM812",
  "E501",
  "PLR0913",
  "RUF013",
  "RUF002",
  "RUF003",
  "F403",
  "RUF001",
  "D",
  "D103",
  "D102",
  "ANN204",
  "FAST001",
  "TD003",
  "TD002",
  "FBT003",
  "FBT001",
  "FBT002",
  "DTZ005",
  "TID252",
  "FIX002",
  "TD004",
  "N805",
  "S104",
  "SIM102",
  "ANN401",
  "B008",
  "TRY003",
  "TRY002",
  "EM101",
]
lint.fixable = ["ALL"]
lint.unfixable = []


line-length = 88
indent-width = 4
target-version = "py312"


[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false

# Ignore specific rules in specific files
[lint.per-file-ignores]
"**/__init__.py" = ["F401"] # Applies to all __init__.py files
